# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://anithapal.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Anitha Palanisamy
  description: "Ruby On Rails developer - Journey " # used by search engines

  # Header and footer text
  header_text: >
     <h1>Anitha Palanisamy</h1>
  header_text_feature_image:
  footer_text: >
   <p> Anitha Palanisamy - 2015 </p>


  # Icons
  rss: false
  email_address: "anithaspark@gmail.com"
  github: "anithaPal"
  linkedin: "https://www.linkedin.com/in/anithapalanisamy"
  medium: "@anithaPal"
  stack_exchange:  # Full URL


  # Scripts
  google_analytics: "UA-69971826-1  " # Tracking ID, e.g. "UA-000000-01"

  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Josefin Slab: 400,600,700"
#  "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 2
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
